### ISSUE TITLE
Engineering 🧰 github.io site

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#37]
### Title

github.io site

### Elevator Pitch

Task one from #31 ! 

### Justification

We need a more accessible site than Tiki-Toki, even if it does lose the fancy timeline feel. GitHub.io will be easier to navigate than the actual repo.

### Skills

| Skill | Rationale |
| --- | --- |
| Coding! | @yochannah's [site](https://github.com/covid19-data-sharing-study/covid19-data-sharing-study.github.io) definitely requires coding skills! |

**Comment by Ismael-KG** [comment]
Template from https://github.com/yochannah/A-History-of-Research-Ethics/blob/24957f6d77247368b596da1d637b119b9fc51b04/Stories/BCE%203250%20Thank%20The%20Scribes!.md

`
---
layout: story
title: ""
historical-date:
  title: "year, explanation"
  source: link
  author: surname(s)
  source-date: year
category: one of the four
tags: ["1", "2","3","4"]
media:
  source: link
  caption: ALT text + source
intro: text
---
`

**Comment by Ismael-KG** [comment]
See [this pull request](https://github.com/yochannah/A-History-of-Research-Ethics/pull/4#issue-1070878799) for a comment on a missing element

**Comment by Ismael-KG** [comment]
New template as per https://github.com/yochannah/A-History-of-Research-Ethics/pull/4#issuecomment-987819016
```
---
layout: story
title: ""
historical-date:
  title: "year, explanation"
  source: link
  author: surname(s)
  source-date: year
category: one of the four
tags: ["1", "2","3","4"]
media:
  source: link
  caption: ALT text + source
read-more: http://whatatevs.com/stuff
intro: text
---
```
